// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	SIWSSBSessions      string
	Aliases             string
	Config              string
	DeniedKeys          string
	FallbackPasswords   string
	FallbackResetTokens string
	Invites             string
	Members             string
	Notices             string
	PinNotices          string
	Pins                string
}{
	SIWSSBSessions:      "SIWSSB_sessions",
	Aliases:             "aliases",
	Config:              "config",
	DeniedKeys:          "denied_keys",
	FallbackPasswords:   "fallback_passwords",
	FallbackResetTokens: "fallback_reset_tokens",
	Invites:             "invites",
	Members:             "members",
	Notices:             "notices",
	PinNotices:          "pin_notices",
	Pins:                "pins",
}
