// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	SIWSSBSessions    string
	Aliases           string
	DeniedKeys        string
	FallbackPasswords string
	Invites           string
	Members           string
	Notices           string
	PinNotices        string
	Pins              string
}{
	SIWSSBSessions:    "SIWSSB_sessions",
	Aliases:           "aliases",
	DeniedKeys:        "denied_keys",
	FallbackPasswords: "fallback_passwords",
	Invites:           "invites",
	Members:           "members",
	Notices:           "notices",
	PinNotices:        "pin_notices",
	Pins:              "pins",
}
